#### dev profile #####
eureka:
  client:
    enabled: false

server:
  port: 8080

spring:
  application:
    name: greetings-service

management:
  security:
    enabled: false

database:
  host: fake-host
  port: 8888
  enable : false