#### default profile #####
eureka:
  client:
    enabled: false

server:
  port: 9090

spring:
  application:
    name: greetings-service

management:
  security:
    enabled: false

database:
  host: prod-host
  port: 9999
  enable : false